name: "PVS Recorder"
description: "Retrieves data for the former SunPower PVS monitoring system"
version: "1.1.3"
slug: "pvs"
init: false
url: https://github.com/sneelco/hassio-addon-pvs
map:
  - share:rw
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
services:
  - mqtt:want
options:
  pvs_host: 172.27.153.1
  pvs_ws_port: 9002
  pvs_ws_secure: false
  mqtt_topic: pvs
  ess_host: 172.27.153.171
  ess_port: 502
  ess_port_503: 503
  ess_devices:
    - device_id: 1
      type: Gateway
      name: Gateway
schema:
  pvs_host: str
  pvs_ws_port: port
  pvs_ws_secure: bool
  ess_host: str
  ess_port: port
  ess_port_503: port
  ess_devices:
    - device_id: int
      type: list(Gateway|Inverter|Bms)
      name: str
  mqtt_host: "str?"
  mqtt_port: "port?"
  mqtt_username: "str?"
  mqtt_password: "password?"
  mqtt_topic: "str"

