name: "PVS Recorder"
description: "Retrieves data for the former SunPower PVS monitoring system"
version: "0.1.1"
slug: "pvs"
init: false
url: https://github.com/sneelco/hassio-addon-pvs
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
services:
  - mqtt:want
options:
  pvs_host: 172.27.153.1
  pvs_ws_port: 9002
  pvs_ws_secure: false
  mqtt_topic: pvs
schema:
  pvs_host: str
  pvs_ws_port: int
  pvs_ws_secure: bool
  mqtt_host: "str?"
  mqtt_port: "port?"
  mqtt_username: "str?"
  mqtt_password: "password?"
  mqtt_topic: "str"

