services:
  nginx:
    image: nginxinc/nginx-unprivileged
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:z
    ports:
      - 9002:9002
      - 9080:9080
      - 5502:5502
      - 5503:5503
      - 5080:5080
      - 5443:5443
